sandbox:
  DOMAIN: DOMAIN_SANDBOX
  BELVO_URL: BELVO_URL_SANDBOX
  BELVO_SECRET_ID: BELVO_SECRET_ID_SANDBOX
  BELVO_SECRET_PASSWORD: BELVO_SECRET_PASSWORD_SANDBOX

dev:
  DOMAIN: DOMAIN_DEV
  BELVO_URL: BELVO_URL_DEV
  BELVO_SECRET_ID: BELVO_SECRET_ID_DEV
  BELVO_SECRET_PASSWORD: BELVO_SECRET_PASSWORD_DEV
  
prod:
  DOMAIN: DOMAIN_PROD
  BELVO_URL: BELVO_URL_PROD
  BELVO_SECRET_ID: BELVO_SECRET_ID_PROD
  BELVO_SECRET_PASSWORD: BELVO_SECRET_PASSWORD_PROD
